language: r
sudo: false
cache: packages
branches:
  only:
    - master

install:
  - R -e "install.packages('devtools')"
  - R -e "devtools::install_github('rstudio/rmarkdown')"    
  - R -e "install.packages('dplyr')"        
  - R -e "install.packages('reshape2')"    
  - R -e "install.packages('ggplot2')"      
  - R -e "install.packages('RColorBrewer')" 
  - R -e "install.packages('readr')"        
  - R -e "install.packages('dataQualityR')"
  - R -e "install.packages('randomForest')" 

script:
  - mkdir dqr/
  - R -e "rmarkdown::render('script.Rmd')"
  - ls

env:
  global:
  - GH_REF: github.com/ColinLeverger/speed-dating-experiment-r.git

after_success:
  - bash ./deploy.sh
